language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

script:
  - ./gradlew assemble

deploy:
  provider: releases
  user: "iplanetcn@gmail.com"
  password: "dlq870720"
  file: app/build/outputs/apk/app-prod-release.apk
  skip_cleanup: true
  on:
    tags: false